### PR TITLE
Rewrite of #8: add SDK to all profiles

### PR DESCRIPTION
**Pull request by ilario**
This PR is for replacing the original one from @egon0 which was stuck since July 2016.
Added  
`CONFIG_SDK=y`
to every profile.

### CODE REVIEW

**Comment by p4u** [comment]
Not sure it is a good idea to compile the SDK. I don't see any real use case where it will be used. In addition we are thinking about changing the approach of lime-build to use the official LEDE sdk release.

Building the SDK takes time and resources so I would not include it.

**Comment by FreifunkUFO** [comment]
yes, SDK is needed when compiling all stuff by our own! 
it would not be needed, if libremesh would use (official) imagebuilder to create firmware (instead of compiling all by ourself)

so, its needed by almost everyone who wants to build own packages or other normal ("libremesh-out-of-scope") openwrt packages and for rebuilding (updated) lede/openwrt packages in the future!

if you dont have enough cpu-power or harddiscs we could help you with that. for testing-purposes you could disable that function temporary, only on your testsystem.

see details:

https://wiki.openwrt.org/doc/howto/obtain.firmware.sdk

also discussions here:
https://github.com/freifunk-berlin/firmware/issues/337

https://github.com/freifunk-gluon/gluon/issues/649

**Comment by ilario** [comment]
I think that the creation of libremesh/lime-sdk by @p4u is related to this

**Comment by ilario** [comment]
So, shall we close this without adding CONFIG_SDK to lime-build?

**Comment by FreifunkUFO** [comment]
ping @p4u

**Pull request closed without merging**
