### PR TITLE
Solving checkout problem if new branch

### PR DESCRIPTION
**Pull request by ilario**
See #4 for description of the problem.

### CODE REVIEW

**Comment by p4u** [comment]
Is this last "git pull" required?

**Comment by ilario** [comment]
Looks working anyway. Ok, I'm going to remove it.

**Comment by altergui** [comment]
sorry to have missed this; i believe this is not the correct way to do it, since "git pull" will try to merge the remote branch into the current branch.

what you really want is a "git remote update", which only fetches remote changes but does not touch the local repository or branches.

**Comment by p4u** [comment]
You are right, pull includes fetch + merge, so it would produce unexpected behaviours.

Acording to github documentation [1], the correct command to fetch a specific branch would be 

git fetch origin branch_name

Should be solved now in commit b242cb2d371e4d0884e28ea50637761f773a643f

[1] https://help.github.com/articles/fetching-a-remote/

**Pull request merged**
